version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: './server'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./server:/api
    ports:
      - "3000:3000"
    depends_on:
      - db

  client:
    build: './client'
    volumes:
      - './client:/home/node/app:rw,consistent'
    working_dir: '/home/node/app'
    command: 'yarn start'
    ports:
      - 127.0.0.1:3001:3000